// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfA3y-GFXSNxR5NrBZtrlHa9PKvNXl81s',
    appId: '1:322883188022:web:9a399caf2d14b9519fef97',
    messagingSenderId: '322883188022',
    projectId: 'chat-app-7192',
    authDomain: 'chat-app-7192.firebaseapp.com',
    storageBucket: 'chat-app-7192.appspot.com',
    measurementId: 'G-QNGNW28GGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkjeu_uPPCbMZCuCQ_pHZACA4blC9JCUQ',
    appId: '1:322883188022:android:dd3ef628b56c751f9fef97',
    messagingSenderId: '322883188022',
    projectId: 'chat-app-7192',
    storageBucket: 'chat-app-7192.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW0V0DDVOtPG1pbFy8_LfF19G3mzRFvJw',
    appId: '1:322883188022:ios:d6c6074530d051c29fef97',
    messagingSenderId: '322883188022',
    projectId: 'chat-app-7192',
    storageBucket: 'chat-app-7192.appspot.com',
    androidClientId: '322883188022-g5i0ivp5vt0trpbb7vottk9icfs7re0v.apps.googleusercontent.com',
    iosClientId: '322883188022-hvbjuro3oagrjnuvc6g6fu5r0dbqfitl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW0V0DDVOtPG1pbFy8_LfF19G3mzRFvJw',
    appId: '1:322883188022:ios:d6c6074530d051c29fef97',
    messagingSenderId: '322883188022',
    projectId: 'chat-app-7192',
    storageBucket: 'chat-app-7192.appspot.com',
    androidClientId: '322883188022-g5i0ivp5vt0trpbb7vottk9icfs7re0v.apps.googleusercontent.com',
    iosClientId: '322883188022-hvbjuro3oagrjnuvc6g6fu5r0dbqfitl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfA3y-GFXSNxR5NrBZtrlHa9PKvNXl81s',
    appId: '1:322883188022:web:8cbfab1ebabc1ff59fef97',
    messagingSenderId: '322883188022',
    projectId: 'chat-app-7192',
    authDomain: 'chat-app-7192.firebaseapp.com',
    storageBucket: 'chat-app-7192.appspot.com',
    measurementId: 'G-Y8NXXKW0RW',
  );

}